// user
export const USER_UPDATING = 'USER_UPDATING';
export const USER_UPDATED = 'USER_UPDATED';

export const USER_RETRIEVING = 'USER_RETRIEVING';
export const USER_RETRIEVED = 'USER_RETRIEVED';

export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const AUTH_ERROR = 'AUTH_ERROR';
export const TOGGLE_AUTH_MODAL = 'TOGGLE_AUTH_MODAL';


// messages
export const GET_MESSAGES = 'GET_MESSAGES';
export const CLEAR_MESSAGES = 'CLEAR_MESSAGES';

// boards
export const BOARDS_LOADING = 'BOARDS_LOADING';
export const BOARDS_LOADED = 'BOARDS_LOADED';
export const BOARDS_FAIL = 'BOARDS_FAIL';

export const BOARD_CREATED = 'BOARD_CREATED';
export const BOARD_CREATING = 'BOARD_CREATING';

// single board
export const SINGLE_BOARD_LOADING = 'SINGLE_BOARD_LOADING';
export const SINGLE_BOARD_LOADED = 'SINGLE_BOARD_LOADED';
export const SINGLE_BOARD_FAIL = 'SINGLE_BOARD_FAIL';

export const SINGLE_BOARD_RENAMING = 'SINGLE_BOARD_RENAMING';
export const SINGLE_BOARD_RENAMED = 'SINGLE_BOARD_RENAMED';

export const SINGLE_BOARD_DELETING = 'SINGLE_BOARD_DELETING';
export const SINGLE_BOARD_DELETED = 'SINGLE_BOARD_DELETED';

// - lists
export const BOARD_LIST_CREATED = 'BOARD_LIST_CREATED';
export const BOARD_LIST_CREATING = 'BOARD_LIST_CREATING';
export const BOARD_LIST_FAIL = 'BOARD_LIST_FAIL';

export const BOARD_LIST_LOADING = 'BOARD_LIST_LOADING';
export const BOARD_LIST_LOADED = 'BOARD_LIST_LOADED';

export const BOARD_LIST_DELETING = 'BOARD_LIST_DELETING';
export const BOARD_LIST_DELETED = 'BOARD_LIST_DELETED';

export const BOARD_LIST_RENAME = 'BOARD_LIST_RENAME';

// - cards
export const BOARD_CARD_CREATING = 'BOARD_CARD_CREATING';
export const BOARD_CARD_CREATED = 'BOARD_CARD_CREATED';
// Drag and Drop
// switch
export const BOARD_CARD_DRAG_DROP_SWITCH = 'BOARD_CARD_DRAG_DROP_SWITCH';
// relocate
export const BOARD_CARD_DRAG_DROP_RELOCATE = 'BOARD_CARD_DRAG_DROP_RELOCATE';


// single card
export const SINGLE_CARD_SELECTED = 'SINGLE_CARD_SELECTED';
export const SINGLE_CARD_UNSELECTED = 'SINGLE_CARD_UNSELECTED';

export const SINGLE_CARD_LOADING = 'SINGLE_CARD_LOADING';
export const SINGLE_CARD_FAIL = 'SINGLE_CARD_FAIL';
export const SINGLE_CARD_LOADED = 'SINGLE_CARD_LOADED';

export const SINGLE_CARD_UPDATING = 'SINGLE_CARD_UPDATING';
export const SINGLE_CARD_UPDATED = 'SINGLE_CARD_UPDATED';

export const SINGLE_CARD_DELETING = 'SINGLE_CARD_DELETING';
export const SINGLE_CARD_DELETED = 'SINGLE_CARD_DELETED';

export const SINGLE_CARD_TODO_CREATING = 'SINGLE_CARD_TODO_CREATING';
export const SINGLE_CARD_TODO_CREATED = 'SINGLE_CARD_TODO_CREATED';


